# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-11 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='orders',
            new_name='order',
        ),
    ]
