# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-31 09:37
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='/workspace/Photography_Website/products/models.py'),
        ),
    ]
