# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-26 06:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Products',
        ),
    ]
