# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-03 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191127_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('A4', '21 x 29.7cm'), ('A3', '29 x 42cm'), ('A3+', '32.9 x 48.3cm')], default='A4', max_length=20),
        ),
    ]
