# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-03 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191203_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('A4', 'A4 = 21 x 29.7cm'), ('A3', 'A3 = 29 x 42cm'), ('A3+', 'A3 = 32.9 x 48.3cm')], max_length=20),
        ),
    ]
