# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-03 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191203_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='signed',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False),
        ),
    ]
